name: test backend application CI/CD pipeline

on:
  pull_request:
    types:
      - "opened"
      - "edited"
      - "reopened"
      - "synchronize"
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout branch"
        uses: actions/checkout@v3

      - name: set env var of current branch name
        run: |
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
          echo $GIT_BRANCH

      - uses: Gr1N/setup-poetry@v8
      - run: poetry --version
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.3"
          cache: "poetry"
      - name: check tests and code style
        run: |
          make install_all
          make lint
          make test
